version: "3.1"
        
        
          
          services:
        
        
          
            jenkins:
        
        
          
              container_name: jenkins
        
        
          
              image: jenkins
        
        
          
              ports:
        
        
          
                - 50000:8080
        
        
          
                - 50001:50000
        
        
          
              volumes:
        
        
          
                - ~/jenkins:/var/jenkins_home
        
        
          
                - /var/run/docker.sock:/var/run/docker.sock
        
        
          
              restart: always